defmodule Mix.Tasks.Bonfire.GenTailwindSources do
  @moduledoc """
  Regenerates `assets/css/_tailwind_sources.css` so Tailwind v4 sees every
  path-dep extension under `/extensions`.

  Tailwind v4 respects `.gitignore` when expanding wildcards in `@source`,
  so a wildcard like `@source "../../../*/lib/..."` silently matches nothing
  for our gitignored extensions. Explicit per-extension `@source` lines DO
  work — this task generates one pair of lines per extension whose `lib/`
  contains Phoenix/Surface templates or LiveView/View modules.
  """
  use Mix.Task

  @shortdoc "Regenerates the Tailwind v4 @source list for /extensions"

  @scan_root "extensions"

  # `_tailwind_sources.css` lives at extensions/bonfire_ui_common/assets/css/,
  # which is 4 directories deep — relative paths must climb 4 levels.
  @ups String.duplicate("../", 4)

  @ui_globs ["**/*.sface", "**/*.heex", "**/*.leex", "**/*_live.ex", "**/*_view.ex"]

  @impl Mix.Task
  def run(_args) do
    packages =
      @scan_root
      |> File.ls!()
      |> Enum.sort()
      |> Enum.map(&Path.join(@scan_root, &1))
      |> Enum.filter(&package_with_ui_files?/1)

    File.write!(output_path(), file_content(packages))

    Mix.shell().info("Wrote #{length(packages)} extension(s) to #{output_path()}")
  end

  defp output_path do
    cond do
      File.dir?("extensions/bonfire_ui_common") ->
        "extensions/bonfire_ui_common/assets/css/_tailwind_sources.css"

      File.dir?("deps/bonfire_ui_common") ->
        "deps/bonfire_ui_common/assets/css/_tailwind_sources.css"

      true ->
        Mix.raise("Could not locate bonfire_ui_common under extensions/ or deps/")
    end
  end

  defp package_with_ui_files?(path) do
    lib = Path.join(path, "lib")
    File.dir?(lib) and Enum.any?(@ui_globs, &(Path.wildcard("#{lib}/#{&1}") != []))
  end

  defp source_lines(package_path) do
    rel = @ups <> package_path

    [
      ~s|@source "#{rel}/lib/**/*.{leex,heex,sface}";|,
      ~s|@source "#{rel}/lib/**/*{_live,_view}.ex";|
    ]
  end

  defp file_content(packages) do
    sources = Enum.flat_map(packages, &source_lines/1)

    """
    /*
     * AUTO-GENERATED by `mix bonfire.gen_tailwind_sources`. Do not edit.
     *
     * One pair of @source lines per extension under /extensions whose lib/
     * contains Phoenix/Surface templates or LiveView/View modules. Tailwind
     * v4 respects .gitignore when expanding wildcards in @source, so the
     * gitignored /extensions tree must be listed explicitly.
     */
    #{Enum.join(sources, "\n")}
    """
  end
end
