defmodule Bonfire.UI.Common.CodeTheme do
  @moduledoc """
  Generates `assets/css/current_code_theme.css`, the syntax highlighting colours for code blocks that `Bonfire.Common.Text` renders with the Lumis `:html_linked` formatter.

  Each Bonfire (daisy) theme picks its Lumis theme in `config :bonfire, :ui, code_themes: %{"light" => "bamboo_light", ...}`. Each entry becomes a block scoped to `[data-theme="<name>"]`. Themes without an entry get an unscoped fallback whose colours are `light-dark(<"light" entry>, <"dark" entry>)`, which resolves against the color-scheme daisyUI sets per theme.

  Called by `Bonfire.UI.Common.TailwindSources.generate/0`, so it runs with the dev watcher and `mix bonfire.gen_tailwind_sources`.
  """
  use Bonfire.Common.Config

  @default_code_themes %{"light" => "bamboo_light", "dark" => "bamboo_vulgaris"}

  def generate do
    path = Bonfire.UI.Common.TailwindSources.css_path("current_code_theme.css")
    File.write!(path, css())
    IO.puts("[CodeTheme] Wrote #{path}")
  end

  def css do
    code_themes = Config.get([:ui, :code_themes], @default_code_themes)

    scoped =
      code_themes
      |> Enum.sort()
      |> Enum.map(fn {bonfire_theme, lumis_theme} ->
        Lumis.Theme.build_css!(lumis_theme, scope: ~s([data-theme="#{bonfire_theme}"]))
      end)

    Enum.join(
      [
        "/* AUTO-GENERATED by Bonfire.UI.Common.CodeTheme, do not edit. Set code themes in `config :bonfire, :ui, code_themes:`. */",
        fallback_css(code_themes) | scoped
      ],
      "\n"
    )
  end

  defp fallback_css(code_themes) do
    light = get_theme!(code_themes["light"] || @default_code_themes["light"])
    dark = get_theme!(code_themes["dark"] || @default_code_themes["dark"])

    highlights =
      Map.new(light.highlights, fn {key, style} ->
        dark_style = dark.highlights[key] || style

        {key,
         %{
           style
           | fg: light_dark(style.fg, dark_style.fg),
             bg: light_dark(style.bg, dark_style.bg)
         }}
      end)

    Lumis.Theme.build_css!(%{
      light
      | name: "#{light.name} / #{dark.name}",
        highlights: highlights
    })
  end

  defp get_theme!(name),
    do:
      Lumis.Theme.get(name) || raise(ArgumentError, "Unknown Lumis code theme: #{inspect(name)}")

  defp light_dark(nil, nil), do: nil
  defp light_dark(light, dark), do: "light-dark(#{light || dark}, #{dark || light})"
end
